### PR TITLE
Update ED link

### PR DESCRIPTION
**Pull request by tyoshino**

### CODE REVIEW

**Comment by yoavweiss** [comment]
@tyoshino - Could you please join the WICG in order to appease the IPR bots? Thanks! :)

**Comment by mikewest** [comment]
Thanks! Since @tyoshino's at Google, his IPR is covered, regardless of the bot's opinion. I'll merge this without waiting for him to formally join.

**Comment by cwilso** [comment]
It's still actually important for @tyoshino to join the WICG (https://www.w3.org/community/wicg/participants, click Join) for tracking purposes and get added to the WICG GH org.  Please do so, or we'll have to back out this commit.

**Comment by tyoshino** [comment]
Sorry for delay. I was swamped for 2 days after sending this PR. I just sent a request to join.

**Comment by tyoshino** [comment]
Joined. Thank you all.

**Pull request merged**
